# Generated by Django 2.0.7 on 2018-07-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider_name', models.CharField(max_length=200)),
                ('Provider_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
