# Generated by Django 2.0.7 on 2018-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20180725_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Provider_UserID',
            field=models.IntegerField(null=True),
        ),
    ]
