# Generated by Django 2.0.7 on 2018-07-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20180725_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Provider_UserID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
