# Generated by Django 2.0.7 on 2018-07-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20180725_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='Provider_UserID',
        ),
    ]
