# Generated by Django 2.0.7 on 2018-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_remove_provider_provider_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='Provider_UserId',
            field=models.IntegerField(null=True),
        ),
    ]
