# Generated by Django 2.0.7 on 2018-07-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_provider_provider_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='Provider_price',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='id',
        ),
        migrations.AlterField(
            model_name='provider',
            name='Provider_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
