# Generated by Django 2.0.7 on 2018-07-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_auto_20180729_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='id',
        ),
        migrations.AlterField(
            model_name='provider',
            name='Provider_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
