# Generated by Django 2.0.7 on 2018-07-29 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_auto_20180729_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Provider_NIP',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Length has to be 10', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='Provider_Phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Atleast 7 and less than 16 digits', regex='^[0-9]{7,16}$')]),
        ),
    ]
