# Generated by Django 2.0.7 on 2018-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer_Name', models.CharField(max_length=200)),
                ('Offer_Date_Published', models.DateTimeField(auto_now_add=True)),
                ('Offer_Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Offer_Ware', models.TextField()),
                ('Offer_Realization_Time', models.CharField(max_length=200)),
                ('Offer_Contact', models.TextField()),
                ('Offer_Expiration_Date', models.DateField()),
            ],
        ),
    ]
