# Generated by Django 2.0.7 on 2018-07-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20180729_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Offer_Ware',
            new_name='Offer_Products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='Offer_Contact',
        ),
        migrations.AddField(
            model_name='offer',
            name='Offer_NIP',
            field=models.CharField(default=1, max_length=68),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='Offer_Phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
