# Generated by Django 2.0.7 on 2018-07-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20180729_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='provider_name',
            field=models.ForeignKey(db_column='Provider_name', on_delete=django.db.models.deletion.CASCADE, to='providers.Provider'),
        ),
    ]
